[package]
name = "pyn-cli"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[[bin]]
name = "pyn"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.7", features = ["derive", "env"] }
pyn-proto = { version = "0.0.1", path = "../pyn-proto" }
reqwest = { version = "0.13.5", default-features = false, features = ["blocking", "json", "query", "rustls"] }
serde = { version = "1.0.229", features = ["derive"] }

[lints]
workspace = true
